# Generated by Django 3.2.8 on 2021-10-26 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_post_tickets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Queras',
            new_name='Quera',
        ),
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
